### ISSUE TITLE
about biliteral_slice question

### ISSUE THREAD

**Issue by alexliyang** [creotiv/hdrnet-pytorch#23]
hi, I trained the model ,and use c++ to infer . in order to do this job .
I split the model to two models : biliteral_grid model and guide model.   then I can get two infer result: coeffs and guidemap.
then I use C++ biliteral_slice op two do slice and applycoeffs , but the result is different from the whole model infer result.
just part of image is right, others part color is very bad and strange. 

I can't understand why ?

ops/ bilateral_slice.cu.cc  C++ code  is equal to F.grid_sample ?

**Comment by alexliyang** [comment]
![hdrnet_outtorchs](https://user-images.githubusercontent.com/31059043/153339717-95814a0d-f9fe-427d-937f-c12cccd0c291.jpg)

**Comment by creotiv** [comment]
@alexliyang F.grid_sample and bilateral slice not equal. They seems do same stuff, but how they do this internally is a question.
And that's a problem, cause somehow model with grid_sample don't want to learn, maybe grid_sample use some logic that breaks gradient for correct passing.

if you want to use cuda code, better to download latest one from original repo https://github.com/google/hdrnet

**Comment by alexliyang** [comment]
thank you very much , now I compile the C++ op， then training again ， useing  C++ version infer is OK

**Comment by creotiv** [comment]
I also added jit compiled version of bilateral slice from original repo. just in case
